[Writable]
LogLevel = 'DEBUG'

[Service]
Host = "edgex-device-mqtt"
Port = 49984
ConnectRetries = 3
Labels = []
OpenMsg = "device mqtt started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "edgex-core-consul"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10
Type = "consul"

[Logging]
EnableRemote = false
File = "./device-mqtt.log"

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 50000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "/custom_config"

# Pre-define Devices
# commentare tutta la sezione [DeviceList.Protocols] in caso di problemi
[[DeviceList]]
  Name = "DISPOSITIVO_CURRENT_PRINTER"
  Profile = "MQTT-CURRENT-PRINTER"
  Description = "PRINTER MQTT device"
  Labels = [ "MQTT"]
  [DeviceList.Protocols]
    [DeviceList.Protocols.mqtt]
       Schema = "tcp"
       Host = "172.17.48.170"
       Port = "1883"
       ClientId = "PrinterClient3"
       User = ""
       Password = ""
       Topic = "test3"
  #[[DeviceList.AutoEvents]]
  #  Frequency = "30s"
  #  OnChange = false
  #  Resource = "testrandnum"

# Driver configs
[Driver]
IncomingSchema = "tcp"
IncomingHost = "172.17.48.170"
IncomingPort = "1883"
IncomingUser = ""
IncomingPassword = ""
IncomingQos = "0"
IncomingKeepAlive = "3600"
IncomingClientId = "IncomingDataSubscriberPri3"
IncomingTopic = "{ver}/Printers/{Id}/Task/Current/pub"
ResponseSchema = "tcp"
ResponseHost = "172.17.48.170"
ResponsePort = "1883"
ResponseUser = ""
ResponsePassword = ""
ResponseQos = "0"
ResponseKeepAlive = "3600"
ResponseClientId = "CommandResponseSubscriberPri3"
ResponseTopic = "ResponseTopicPri3"
ConnEstablishingRetry = "3"
ConnRetryWaitTime = "3000"
